# Generated by Django 6.1 on 2026-08-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_options_remove_movie_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
