# Generated by Django 6.1.1 on 2026-09-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente'), ('Credito', 'Credito')], max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='transacciones.usuario')),
            ],
        ),
    ]
