# Generated by Django 6.1.1 on 2026-09-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentabancaria",
            name="tope_gasto_mensual",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cuentabancaria",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Ahorros", "Cuenta de Ahorros"),
                    ("Corriente", "Cuenta Corriente"),
                    ("Billetera Digital", "Billetera Digital"),
                    ("Tarjeta de Crédito", "Tarjeta de Crédito"),
                ],
                default="Ahorros",
                max_length=30,
            ),
        ),
    ]
