# Generated by Django 6.1.1 on 2026-09-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_cuentabancaria_tope_gasto_mensual_and_more"),
        (
            "transacciones",
            "0002_alter_transaccion_cuenta_alter_transaccion_fecha_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("servicio_preset", models.CharField(default="otro", max_length=50)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[("Mensual", "Mensual"), ("Anual", "Anual")],
                        default="Mensual",
                        max_length=20,
                    ),
                ),
                ("fecha_proximo_pago", models.DateField()),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="app.cuentabancaria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="transacciones.usuario",
                    ),
                ),
            ],
        ),
    ]
