# Generated by Django 6.1.1 on 2026-09-30 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_metaahorro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('general', 'General'), ('cuentas', 'Cuentas'), ('gastos', 'Gastos'), ('metas', 'Metas de Ahorro'), ('suscripciones', 'Suscripciones'), ('reportes', 'Reportes y Estadísticas')], max_length=20)),
                ('contenido', models.TextField()),
                ('tokens_usados', models.IntegerField(default=0)),
                ('trigger', models.CharField(choices=[('weekly', 'Semanal'), ('new_meta', 'Nueva Meta'), ('new_suscripcion', 'Nueva Suscripción'), ('large_gasto', 'Gasto Grande'), ('meta_cumplida', 'Meta Cumplida'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seccion'],
                'unique_together': {('usuario', 'seccion')},
            },
        ),
    ]
